### ISSUE TITLE
is this up-to-date?

### ISSUE THREAD

**Issue by ewerybody** [friedererdmann/blender_studio_scripts#3]
Hey @friedererdmann cheers!
I wonder if this is still the goto-method for pulling off "studio-addons" packages?
We have a similar hack in place kicked off from `%APPDATA%\Blender Foundation\Blender\X.X\scripts\startup`. But there are issues loading from there somehow.

Meanwhile there seems to be this **Script Directories** field under **Preferences > File Paths** in Blender. And that works as well. I just havent looked into setting it from the outside. Maybe you know more? :)

**Comment by ewerybody** [comment]
Alright I found out how to pull this off now. For the record:
```py
new_dir = bpy.context.preferences.filepaths.script_directories.new()
new_dir.name = 'MyToolsDir'
new_dir.directory = r'C:\somedir\MyToolsDir'
```
to enlist a custom directory. These are persistent though! Check upfront if its already listed liek:
```py
my_tools_path = r'C:\somedir\MyToolsDir'
for directory in bpy.context.preferences.filepaths.script_directories:
    if dir_object.directory == my_tools_path:
        break
else:
    # do the enlisting ... ^
```

**Comment by friedererdmann** [comment]
Hi Eric! Long time no see! Sorry I didn't see your comment earlier! Yeah, the script directories solve the same problem, but potentially mess with virtualization, since they will be persistently stored (so if the user switches the project/environment, it might still pick up on scripts elsewhere).

**Comment by ewerybody** [comment]
Hey Hello :) yeah quite a while!
Well, we just solved all the things with the script dirs. Recently there was someone with autosave prefs OFF. So doing anything with the script dirs on startup didn't work 🙈. Well, now they wanna go extensions. Lets see how that goes.
